# GENERAL_OPTIONS
seed: 58      # Experiment random seed
use_gpu: True     # If True, train VAE on GPU
tensorboard_log_dir: 'tensorboard'       # Tensorboard log directory
log_dir: 'log'     # Logger log directory
dataset_name: 'synthetic'     # Dataset name, including ['synthetic', 'ACSIncome']
task: 'classification'   #  classification or regression
source_state:
target_state:
is_transfer: True
early_stop: True
# TRAINING_OPTIONS
vae_epochs: 500    # Training epochs of VAE
batch_size: 30000      # Batch size of VAE loaders
vae_lr: 1e-4      # Learning rate of VAE
disc_lr: 1e-5     # Learning rate of VAE discriminator for Total Correlation
mlp_lr: 1e-4      # Learning rate of MLP classifier
mlp_hidden_layers: [128, 128, 128]      # Hidden layers of MLP classifier
clf_mlp_epochs: 500   # Training epochs of MLP classifier
use_torch_mlp: True     # If True, use torch NN and will be trained on GPU. If False, use sklearn MLPClassifier
draw_tSNE: False
# MODEL_Structure
un_dim: 3     # Latent variable Un dim
ua_dim: 3     # Latent variable Ua dim
uy_dim: ~     # Latent variable Uy dim
h_dim: 100      # Hidden layer dim for encoder and decoder in VAE
h_layers: 3     # Hidden layer numbers for encoder and decoder in VAE
act_fn: 'leakyrelu'     # Act function for encoder and decoder in VAE
disc_h_dim: 100     # Hidden layer numbers for discriminator for Total Correlation
disc_h_layers: 3      # Hidden layer numbers for discriminator for Total Correlation
parm_r_xn: 1.0
parm_r_xa: 1.0
parm_r_y: 1.0
parm_kl: 0.1
parm_tc: 1.0
parm_css: 1.0
parm_tf: 1e-4